from homeassistant.components.climate.const import (
    HVACMode,
    ClimateEntityFeature,
    FAN_AUTO,
    FAN_LOW,
    FAN_MEDIUM,
    FAN_HIGH,
    SWING_OFF,
    SWING_HORIZONTAL,
    SWING_VERTICAL,
    SWING_BOTH,
)
from pysyncleo.enums import UdpCommandType

from ..const import (
    FAN_MAX,
    FAN_MID_HIGH,
    FAN_MID_LOW,
    FAN_MIN,
    FAN_QUITE,
    FAN_TURBO,
    FEATURE_ACCESS_CONTROL,
    FEATURE_ANTI_MELDEW,
    FEATURE_AURUS_VRF_CHILD_LOCK,
    FEATURE_AURUS_VRF_ECO_MODE,
    FEATURE_AURUS_VRF_NOISELESS_MODE,
    FEATURE_BACKLIGHT,
    FEATURE_CHILD_LOCK,
    FEATURE_ERROR,
    FEATURE_GOLDSTAR_GSTI_BREEZE_AWAY,
    FEATURE_GOLDSTAR_GSTI_CLEAN,
    FEATURE_GOLDSTAR_GSTI_DAMPER,
    FEATURE_GOLDSTAR_GSTI_FREEZE_PROTECTION,
    FEATURE_IONIZATION,
    FEATURE_NIGHT,
    FEATURE_ECO_AS_SMART_MODE,
    FEATURE_SHUFT_SFMS_09_ANTI_MELDEW,
    FEATURE_SHUFT_SFMS_07_09_FREEZE_PROTECTION,
    FEATURE_TURBO,
    FEATURE_VOLUME,
    PD_ANGLE_HORIZONTAL,
    PD_ANGLE_VERTICAL,
    PD_AURUS_A_AIR_CLEAN,
    PD_AURUS_SCREENSAVER_MODE,
    PD_BREEZE_AWAY,
    PD_DISPLAY_HALF_POWER,
    PD_ENERGY_SAVING,
    PD_FIREPLACE,
    PD_FREEZE_PROTECTION,
    PD_FUNGUS_PROOF,
    PD_LAST_PROGRAM,
    PD_NOISELESS,
    PD_POWER,
    PD_SELFCLEAN,
    PD_SILENCE_MODE,
    PD_SWING_HORIZONTAL,
    PD_SWING_VERTICAL,
    PD_TURN_ON,
    PRESET_AURUS_SCREENSAVER_MODE_1,
    PRESET_AURUS_SCREENSAVER_MODE_3,
    PRESET_AURUS_SCREENSAVER_MODE_5,
    PRESET_AURUS_SCREENSAVER_MODE_OFF,
    PRESET_NIGHT_MODE_AGED,
    PRESET_NIGHT_MODE_CHILD,
    PRESET_NIGHT_MODE_OFF,
    PRESET_NIGHT_MODE_STANDARD,
    PRESET_NIGHT_MODE_TEEN,
    PRESET_TOSHIBA_NOISELESS_1,
    PRESET_TOSHIBA_NOISELESS_2,
    PRESET_TOSHIBA_NOISELESS_OFF,
    PRESET_TOSHIBA_POWER_100,
    PRESET_TOSHIBA_POWER_50,
    PRESET_TOSHIBA_POWER_75,
    VENDOR_RUSCLIMATE,
)
from .profiles import AirConditionerProfile, ProgramDataField, SelectConfig

PROFILES = [
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=8,
        min_temp=17,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={FAN_AUTO: 0, FAN_LOW: 1, FAN_MEDIUM: 2, FAN_HIGH: 3},
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
        },
        binary_sensors=[
            FEATURE_ACCESS_CONTROL,
            FEATURE_BACKLIGHT,
            FEATURE_CHILD_LOCK,
            FEATURE_ERROR,
            FEATURE_VOLUME,
        ],
        switches=[FEATURE_NIGHT, FEATURE_TURBO],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=10,
        min_temp=18,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.FAN_ONLY,
        fan_modes_map={FAN_AUTO: 0, FAN_LOW: 1, FAN_MEDIUM: 2, FAN_HIGH: 3},
        supported_swing_modes=[
            SWING_OFF,
            SWING_HORIZONTAL,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_LAST_PROGRAM: ProgramDataField(
                mode=0, offset=1, min_value=2, max_value=5
            ),
        },
        binary_sensors=[
            FEATURE_ERROR,
        ],
        switches=[FEATURE_NIGHT],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=13,
        min_temp=16,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_MIN: 1,
            FAN_LOW: 2,
            FAN_MEDIUM: 3,
            FAN_HIGH: 4,
            FAN_MAX: 5,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
            PD_BREEZE_AWAY: ProgramDataField(mode=2),
            PD_ANGLE_HORIZONTAL: ProgramDataField(mode=3, max_value=5),
            PD_ANGLE_VERTICAL: ProgramDataField(mode=4, max_value=5),
        },
        binary_sensors=[
            FEATURE_ERROR,
        ],
        numbers=[PD_ANGLE_HORIZONTAL, PD_ANGLE_VERTICAL],
        switches=[
            FEATURE_NIGHT,
            FEATURE_TURBO,
            PD_BREEZE_AWAY,
            PD_ENERGY_SAVING,
            PD_FREEZE_PROTECTION,
            PD_SELFCLEAN,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=15,
        min_temp=16,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_MIN: 1,
            FAN_LOW: 2,
            FAN_MEDIUM: 3,
            FAN_HIGH: 4,
            FAN_MAX: 5,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0, max_value=6),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1, max_value=6),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
        },
        binary_sensors=[
            FEATURE_ERROR,
        ],
        numbers=[PD_SWING_HORIZONTAL, PD_SWING_VERTICAL],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_IONIZATION,
            FEATURE_NIGHT,
            FEATURE_TURBO,
            PD_ENERGY_SAVING,
            PD_FREEZE_PROTECTION,
            PD_SELFCLEAN,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=20,
        min_temp=16,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={FAN_AUTO: 0, FAN_LOW: 1, FAN_MEDIUM: 2, FAN_HIGH: 3},
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FUNGUS_PROOF: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
            PD_SILENCE_MODE: ProgramDataField(mode=1, offset=1),
        },
        binary_sensors=[
            FEATURE_ERROR,
        ],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_IONIZATION,
            FEATURE_NIGHT,
            FEATURE_TURBO,
            PD_ENERGY_SAVING,
            PD_FUNGUS_PROOF,
            PD_SELFCLEAN,
            PD_SILENCE_MODE,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=21,
        min_temp=18,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={FAN_AUTO: 0, FAN_LOW: 1, FAN_MEDIUM: 2, FAN_HIGH: 3},
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_SILENCE_MODE: ProgramDataField(mode=0, offset=3),
        },
        binary_sensors=[
            FEATURE_ACCESS_CONTROL,
            FEATURE_CHILD_LOCK,
            FEATURE_ERROR,
            FEATURE_VOLUME,
        ],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_NIGHT,
            FEATURE_TURBO,
            PD_ENERGY_SAVING,
            PD_SILENCE_MODE,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=38,
        min_temp=17,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_MIN: 2,
            FAN_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_HIGH: 5,
            FAN_MAX: 6,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_POWER: ProgramDataField(mode=1, max_value=2),
            PD_FIREPLACE: ProgramDataField(mode=1, offset=2),
            PD_NOISELESS: ProgramDataField(mode=1, offset=3, max_value=2),
            PD_TURN_ON: ProgramDataField(mode=1, offset=4),
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            PD_POWER: SelectConfig(
                options_map={
                    PRESET_TOSHIBA_POWER_50: 0,
                    PRESET_TOSHIBA_POWER_75: 1,
                    PRESET_TOSHIBA_POWER_100: 2,
                }
            ),
            PD_NOISELESS: SelectConfig(
                options_map={
                    PRESET_TOSHIBA_NOISELESS_OFF: 0,
                    PRESET_TOSHIBA_NOISELESS_1: 1,
                    PRESET_TOSHIBA_NOISELESS_2: 2,
                }
            ),
        },
        switches=[FEATURE_TURBO, PD_ENERGY_SAVING, PD_FREEZE_PROTECTION, PD_FIREPLACE],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=41,
        min_temp=16,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_MIN: 1,
            FAN_MEDIUM: 2,
            FAN_MAX: 3,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0, max_value=6),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1, max_value=6),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_SWING_HORIZONTAL, PD_SWING_VERTICAL],
        switches=[
            FEATURE_IONIZATION,
            FEATURE_NIGHT,
            FEATURE_TURBO,
            PD_ENERGY_SAVING,
            PD_FREEZE_PROTECTION,
            PD_SELFCLEAN,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=51,
        min_temp=18,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.FAN_ONLY,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_LOW: 1,
            FAN_HIGH: 2,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_HORIZONTAL,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_LAST_PROGRAM: ProgramDataField(
                mode=0, offset=1, min_value=2, max_value=5
            ),
        },
        binary_sensors=[
            FEATURE_ERROR,
        ],
        switches=[FEATURE_NIGHT],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=55,
        min_temp=16,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MID_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_MID_HIGH: 5,
            FAN_HIGH: 6,
            FAN_TURBO: 7,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
            PD_BREEZE_AWAY: ProgramDataField(mode=2),
            PD_ANGLE_HORIZONTAL: ProgramDataField(mode=3, max_value=5),
            PD_ANGLE_VERTICAL: ProgramDataField(mode=4, max_value=5),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_ANGLE_HORIZONTAL, PD_ANGLE_VERTICAL],
        selects={
            FEATURE_NIGHT: SelectConfig(
                options_map={
                    PRESET_NIGHT_MODE_OFF: 0,
                    PRESET_NIGHT_MODE_STANDARD: 1,
                    PRESET_NIGHT_MODE_CHILD: 2,
                    PRESET_NIGHT_MODE_AGED: 3,
                }
            )
        },
        switches=[
            FEATURE_ANTI_MELDEW,
            FEATURE_BACKLIGHT,
            FEATURE_VOLUME,
            PD_ENERGY_SAVING,
            PD_FREEZE_PROTECTION,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=56,
        min_temp=17,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_MIN: 2,
            FAN_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_HIGH: 5,
            FAN_MAX: 6,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0, max_value=6),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_POWER: ProgramDataField(mode=1, max_value=2),
            PD_FIREPLACE: ProgramDataField(mode=1, offset=1),
            PD_NOISELESS: ProgramDataField(mode=1, offset=2, max_value=2),
            PD_TURN_ON: ProgramDataField(mode=1, offset=3),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_SWING_HORIZONTAL],
        selects={
            PD_POWER: SelectConfig(
                options_map={
                    PRESET_TOSHIBA_POWER_50: 0,
                    PRESET_TOSHIBA_POWER_75: 1,
                    PRESET_TOSHIBA_POWER_100: 2,
                }
            ),
            PD_NOISELESS: SelectConfig(
                options_map={
                    PRESET_TOSHIBA_NOISELESS_OFF: 0,
                    PRESET_TOSHIBA_NOISELESS_1: 1,
                    PRESET_TOSHIBA_NOISELESS_2: 2,
                }
            ),
        },
        switches=[
            FEATURE_IONIZATION,
            FEATURE_TURBO,
            PD_ENERGY_SAVING,
            PD_FIREPLACE,
            PD_FREEZE_PROTECTION,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=57,
        min_temp=16,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_LOW: 1,
            FAN_MEDIUM: 2,
            FAN_HIGH: 3,
            FAN_TURBO: 4,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
        },
        binary_sensors=[FEATURE_ERROR],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_NIGHT,
            PD_ENERGY_SAVING,
            PD_FREEZE_PROTECTION,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=60,
        min_temp=16,
        max_temp=31,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MID_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_MID_HIGH: 5,
            FAN_HIGH: 6,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
            PD_BREEZE_AWAY: ProgramDataField(mode=2),
            PD_ANGLE_HORIZONTAL: ProgramDataField(mode=3, max_value=5),
            PD_ANGLE_VERTICAL: ProgramDataField(mode=4, max_value=5),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_ANGLE_HORIZONTAL, PD_ANGLE_VERTICAL],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_NIGHT,
            FEATURE_VOLUME,
            PD_ENERGY_SAVING,
            PD_FREEZE_PROTECTION,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=68,
        min_temp=16,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MEDIUM: 3,
            FAN_HIGH: 4,
            FAN_MAX: 5,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
        },
        binary_sensors=[
            FEATURE_ACCESS_CONTROL,
            FEATURE_CHILD_LOCK,
            FEATURE_ERROR,
            FEATURE_VOLUME,
        ],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_NIGHT,
            PD_ENERGY_SAVING,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=70,
        min_temp=16,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_LOW: 1,
            FAN_MEDIUM: 2,
            FAN_HIGH: 3,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FUNGUS_PROOF: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
            PD_SILENCE_MODE: ProgramDataField(mode=1, offset=1),
        },
        binary_sensors=[FEATURE_ERROR],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_NIGHT,
            FEATURE_TURBO,
            PD_ENERGY_SAVING,
            PD_FUNGUS_PROOF,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=72,
        min_temp=16,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MID_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_MID_HIGH: 5,
            FAN_HIGH: 6,
            FAN_TURBO: 7,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
            PD_BREEZE_AWAY: ProgramDataField(mode=2),
            PD_ANGLE_HORIZONTAL: ProgramDataField(mode=3, max_value=5),
            PD_ANGLE_VERTICAL: ProgramDataField(mode=4, max_value=5),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_ANGLE_HORIZONTAL, PD_ANGLE_VERTICAL],
        selects={
            FEATURE_NIGHT: SelectConfig(
                options_map={
                    PRESET_NIGHT_MODE_OFF: 0,
                    PRESET_NIGHT_MODE_STANDARD: 1,
                    PRESET_NIGHT_MODE_CHILD: 2,
                    PRESET_NIGHT_MODE_AGED: 3,
                }
            )
        },
        switches=[
            FEATURE_ANTI_MELDEW,
            FEATURE_BACKLIGHT,
            FEATURE_VOLUME,
            PD_ENERGY_SAVING,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=82,
        min_temp=16,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={FAN_AUTO: 0, FAN_LOW: 1, FAN_MEDIUM: 2, FAN_HIGH: 3},
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
        },
        binary_sensors=[FEATURE_ERROR],
        switches=[FEATURE_BACKLIGHT, FEATURE_NIGHT, FEATURE_TURBO],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=83,
        min_temp=16,
        max_temp=30,
        supported_features=(
            ClimateEntityFeature.TARGET_TEMPERATURE
            | ClimateEntityFeature.FAN_MODE
            | ClimateEntityFeature.TURN_ON
            | ClimateEntityFeature.TURN_OFF
        ),
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.COOL,
        fan_modes_map={FAN_LOW: 1, FAN_HIGH: 2},
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_LAST_PROGRAM: ProgramDataField(mode=0, offset=1, max_value=5),
        },
        binary_sensors=[FEATURE_ERROR],
        switches=[FEATURE_NIGHT],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=84,
        min_temp=16,
        max_temp=30,
        supported_features=(
            ClimateEntityFeature.TARGET_TEMPERATURE
            | ClimateEntityFeature.FAN_MODE
            | ClimateEntityFeature.TURN_ON
            | ClimateEntityFeature.TURN_OFF
        ),
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.COOL,
        fan_modes_map={FAN_LOW: 1, FAN_HIGH: 2},
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_LAST_PROGRAM: ProgramDataField(mode=0, offset=1, max_value=5),
        },
        binary_sensors=[FEATURE_ERROR],
        switches=[FEATURE_NIGHT],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=85,
        min_temp=16,
        max_temp=30,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_MIN: 2,
            FAN_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_HIGH: 5,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0, max_value=6),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1, max_value=6),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_LAST_PROGRAM: ProgramDataField(mode=0, offset=4),
            PD_SELFCLEAN: ProgramDataField(mode=1),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_SWING_HORIZONTAL, PD_SWING_VERTICAL],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_NIGHT,
            FEATURE_TURBO,
            FEATURE_VOLUME,
            PD_FREEZE_PROTECTION,
            PD_SELFCLEAN,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=95,
        min_temp=17,
        max_temp=30,
        supported_features=(
            ClimateEntityFeature.TARGET_TEMPERATURE
            | ClimateEntityFeature.FAN_MODE
            | ClimateEntityFeature.TURN_ON
            | ClimateEntityFeature.TURN_OFF
        ),
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={FAN_AUTO: 0, FAN_LOW: 1, FAN_MEDIUM: 2, FAN_HIGH: 3},
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_SELFCLEAN: ProgramDataField(mode=1),
        },
        binary_sensors=[FEATURE_BACKLIGHT, FEATURE_ERROR],
        switches=[FEATURE_NIGHT, FEATURE_TURBO],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=99,
        min_temp=16,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MEDIUM: 3,
            FAN_HIGH: 4,
            FAN_MAX: 5,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
            PD_AURUS_A_AIR_CLEAN: ProgramDataField(mode=1, offset=1),
            PD_NOISELESS: ProgramDataField(mode=1, offset=2),
            PD_BREEZE_AWAY: ProgramDataField(mode=2),
            PD_ANGLE_HORIZONTAL: ProgramDataField(mode=3, max_value=6),
            PD_ANGLE_VERTICAL: ProgramDataField(mode=4, max_value=5),
        },
        binary_sensors=[
            FEATURE_ACCESS_CONTROL,
            FEATURE_CHILD_LOCK,
            FEATURE_ERROR,
            FEATURE_VOLUME,
        ],
        numbers=[PD_ANGLE_HORIZONTAL, PD_ANGLE_VERTICAL],
        selects={
            FEATURE_NIGHT: SelectConfig(
                options_map={
                    PRESET_NIGHT_MODE_OFF: 0,
                    PRESET_NIGHT_MODE_STANDARD: 1,
                    PRESET_NIGHT_MODE_CHILD: 2,
                    PRESET_NIGHT_MODE_TEEN: 3,
                    PRESET_NIGHT_MODE_AGED: 4,
                }
            )
        },
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_ECO_AS_SMART_MODE,
            FEATURE_TURBO,
            PD_AURUS_A_AIR_CLEAN,
            PD_ENERGY_SAVING,
            PD_FREEZE_PROTECTION,
            PD_NOISELESS,
            PD_SELFCLEAN,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=108,
        min_temp=16,
        max_temp=31,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MID_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_MID_HIGH: 5,
            FAN_HIGH: 6,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1),
            PD_ENERGY_SAVING: ProgramDataField(mode=0, offset=2),
            PD_FREEZE_PROTECTION: ProgramDataField(mode=0, offset=3),
            PD_SELFCLEAN: ProgramDataField(mode=1),
            PD_BREEZE_AWAY: ProgramDataField(mode=2),
            PD_ANGLE_HORIZONTAL: ProgramDataField(mode=3, max_value=5),
            PD_ANGLE_VERTICAL: ProgramDataField(mode=4, max_value=5),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_ANGLE_HORIZONTAL, PD_ANGLE_VERTICAL],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_NIGHT,
            FEATURE_ECO_AS_SMART_MODE,
            FEATURE_VOLUME,
            PD_FREEZE_PROTECTION,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=110,
        min_temp=16,
        max_temp=31,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MID_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_MID_HIGH: 5,
            FAN_HIGH: 6,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_VERTICAL,
            SWING_HORIZONTAL,
            SWING_BOTH,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0, max_value=8),
            PD_SWING_VERTICAL: ProgramDataField(mode=0, offset=1, max_value=9),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_SWING_HORIZONTAL, PD_SWING_VERTICAL],
        selects={
            FEATURE_NIGHT: SelectConfig(
                options_map={
                    PRESET_NIGHT_MODE_OFF: 0,
                    PRESET_NIGHT_MODE_STANDARD: 1,
                    PRESET_NIGHT_MODE_CHILD: 2,
                    PRESET_NIGHT_MODE_AGED: 3,
                }
            )
        },
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_ECO_AS_SMART_MODE,
            FEATURE_GOLDSTAR_GSTI_BREEZE_AWAY,
            FEATURE_GOLDSTAR_GSTI_CLEAN,
            FEATURE_GOLDSTAR_GSTI_DAMPER,
            FEATURE_GOLDSTAR_GSTI_FREEZE_PROTECTION,
            FEATURE_TURBO,
            FEATURE_VOLUME,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=111,
        min_temp=16,
        max_temp=31,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MID_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_MID_HIGH: 5,
            FAN_HIGH: 6,
            FAN_TURBO: 7,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_HORIZONTAL,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_ANGLE_HORIZONTAL: ProgramDataField(mode=3, max_value=5),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_ANGLE_HORIZONTAL],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_ECO_AS_SMART_MODE,
            FEATURE_VOLUME,
            FEATURE_SHUFT_SFMS_09_ANTI_MELDEW,
            FEATURE_SHUFT_SFMS_07_09_FREEZE_PROTECTION,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=114,
        min_temp=16,
        max_temp=31,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_LOW: 2,
            FAN_MID_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_MID_HIGH: 5,
            FAN_HIGH: 6,
            FAN_TURBO: 7,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_HORIZONTAL,
        ],
        program_data_fields={
            PD_SWING_HORIZONTAL: ProgramDataField(mode=0),
            PD_ANGLE_HORIZONTAL: ProgramDataField(mode=3, max_value=5),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_ANGLE_HORIZONTAL],
        switches=[
            FEATURE_BACKLIGHT,
            FEATURE_TURBO,
            FEATURE_VOLUME,
            FEATURE_SHUFT_SFMS_07_09_FREEZE_PROTECTION,
        ],
    ),
    AirConditionerProfile(
        vendor=VENDOR_RUSCLIMATE,
        device_type=120,
        min_temp=16,
        max_temp=32,
        hvac_modes_map={
            HVACMode.OFF: 0,
            HVACMode.AUTO: 1,
            HVACMode.COOL: 2,
            HVACMode.DRY: 3,
            HVACMode.HEAT: 4,
            HVACMode.FAN_ONLY: 5,
        },
        default_hvac_mode=HVACMode.AUTO,
        cmd_current_humidity=UdpCommandType.CURRENT_HUMIDITY,
        fan_modes_map={
            FAN_AUTO: 0,
            FAN_QUITE: 1,
            FAN_MIN: 2,
            FAN_LOW: 3,
            FAN_MEDIUM: 4,
            FAN_HIGH: 5,
            FAN_MAX: 6,
        },
        supported_swing_modes=[
            SWING_OFF,
            SWING_HORIZONTAL,
        ],
        program_data_fields={
            PD_LAST_PROGRAM: ProgramDataField(mode=0, max_value=5),
            PD_SWING_HORIZONTAL: ProgramDataField(mode=1, max_value=5),
            PD_DISPLAY_HALF_POWER: ProgramDataField(mode=2),
            PD_AURUS_SCREENSAVER_MODE: ProgramDataField(mode=3),
        },
        binary_sensors=[FEATURE_ERROR],
        numbers=[PD_SWING_HORIZONTAL],
        selects={
            PD_AURUS_SCREENSAVER_MODE: SelectConfig(
                options_map={
                    PRESET_AURUS_SCREENSAVER_MODE_OFF: 0,
                    PRESET_AURUS_SCREENSAVER_MODE_1: 1,
                    PRESET_AURUS_SCREENSAVER_MODE_3: 2,
                    PRESET_AURUS_SCREENSAVER_MODE_5: 3,
                },
            ),
        },
        switches=[
            FEATURE_AURUS_VRF_CHILD_LOCK,
            FEATURE_AURUS_VRF_ECO_MODE,
            FEATURE_AURUS_VRF_NOISELESS_MODE,
            FEATURE_BACKLIGHT,
            FEATURE_IONIZATION,
            FEATURE_TURBO,
            FEATURE_VOLUME,
        ],
    ),
]
