from homeassistant.components.water_heater import STATE_OFF

from ..const import (
    FEATURE_BACKLIGHT,
    FEATURE_CHILD_LOCK,
    FEATURE_ERROR,
    FEATURE_KETTLE_TEMPERATURE_PRESET,
    FEATURE_VOLUME,
    KETTLE_MODE_BOILING,
    KETTLE_MODE_IQ_BOILING,
    KETTLE_MODE_TEA_TIME,
    KETTLE_MODE_WARM_UP,
    KETTLE_MODE_WARM_UP_KEEP,
    KETTLE_PRESET_BABY_BOTTLE,
    KETTLE_PRESET_BLACK_TEA,
    KETTLE_PRESET_FLOWER_TEA,
    KETTLE_PRESET_GREEN_TEA,
    KETTLE_PRESET_HERBAL_TEA,
    KETTLE_PRESET_INSTANT_COFFEE,
    KETTLE_PRESET_NONE,
    KETTLE_PRESET_OOLONG_TEA,
    KETTLE_PRESET_PUER,
    KETTLE_PRESET_RED_TEA,
    KETTLE_PRESET_TEA_BAG,
    KETTLE_PRESET_WHITE_TEA,
    VENDOR_POLARIS,
)
from .profiles import KettleProfile, SelectConfig

PROFILES = [
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=2,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_CHILD_LOCK],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=35,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=51,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=56,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=60,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=98,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=188,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=223,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=262,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=263,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=275,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
    KettleProfile(
        vendor=VENDOR_POLARIS,
        device_type=294,
        default_operation_mode=KETTLE_MODE_BOILING,
        operation_modes_map={
            STATE_OFF: 0,
            KETTLE_MODE_BOILING: 1,
            KETTLE_MODE_WARM_UP: 3,
            KETTLE_MODE_WARM_UP_KEEP: 4,
            KETTLE_MODE_IQ_BOILING: 5,
            KETTLE_MODE_TEA_TIME: 6,
        },
        binary_sensors=[FEATURE_ERROR],
        selects={
            FEATURE_KETTLE_TEMPERATURE_PRESET: SelectConfig(
                options_map={
                    KETTLE_PRESET_NONE: 0,
                    KETTLE_PRESET_BLACK_TEA: 100,
                    KETTLE_PRESET_BABY_BOTTLE: 40,
                    KETTLE_PRESET_INSTANT_COFFEE: 95,
                    KETTLE_PRESET_GREEN_TEA: 80,
                    KETTLE_PRESET_FLOWER_TEA: 80,
                    KETTLE_PRESET_TEA_BAG: 100,
                    KETTLE_PRESET_RED_TEA: 90,
                    KETTLE_PRESET_PUER: 95,
                    KETTLE_PRESET_OOLONG_TEA: 90,
                    KETTLE_PRESET_WHITE_TEA: 65,
                    KETTLE_PRESET_HERBAL_TEA: 90,
                }
            ),
        },
        switches=[FEATURE_BACKLIGHT, FEATURE_CHILD_LOCK, FEATURE_VOLUME],
    ),
]
