DOMAIN = "syncleo"

VENDOR_RUSCLIMATE = "rusclimate"
VENDOR_POLARIS = "polaris"

CONF_ATTRIBUTES = "attributes"
CONF_FIRMWARE = "firmware"
CONF_MANUFACTURER = "manufacturer"
CONF_PROTOCOL = "protocol"
CONF_PUBLIC_KEY = "public"
CONF_VENDOR = "vendor"

FAN_MAX = "max"
FAN_MID_HIGH = "mid_high"
FAN_MID_LOW = "mid_low"
FAN_MIN = "min"
FAN_QUITE = "quite"
FAN_TURBO = "turbo"

KETTLE_MODE_BOILING = "boiling"
KETTLE_MODE_BOILING_KEEP = "boiling_keep"
KETTLE_MODE_WARM_UP = "warm_up"
KETTLE_MODE_WARM_UP_KEEP = "warm_up_keep"
KETTLE_MODE_IQ_BOILING = "iq_boiling"
KETTLE_MODE_TEA_TIME = "tea_time"

KETTLE_PRESET_NONE = "kettle_preset_none"
KETTLE_PRESET_BLACK_TEA = "kettle_preset_black_tea"
KETTLE_PRESET_BABY_BOTTLE = "kettle_preset_baby_bottle"
KETTLE_PRESET_INSTANT_COFFEE = "kettle_preset_instant_coffee"
KETTLE_PRESET_GREEN_TEA = "kettle_preset_green_tea"
KETTLE_PRESET_FLOWER_TEA = "kettle_preset_flower_tea"
KETTLE_PRESET_TEA_BAG = "kettle_preset_tea_bag"
KETTLE_PRESET_RED_TEA = "kettle_preset_red_tea"
KETTLE_PRESET_PUER = "kettle_preset_puer"
KETTLE_PRESET_OOLONG_TEA = "kettle_preset_oolong_tea"
KETTLE_PRESET_WHITE_TEA = "kettle_preset_white_tea"
KETTLE_PRESET_HERBAL_TEA = "kettle_preset_herbal_tea"

PD_ANGLE_HORIZONTAL = "angle_horizontal"
PD_ANGLE_VERTICAL = "angle_vertical"
PD_ANTI_FROST_TEMP = "anti_frost_temp"
PD_AUTO_OFF_DISPLAY = "auto_off_display"
PD_BREEZE_AWAY = "breeze_away"
PD_CO2_INSTALLED = "co2_installed"
PD_UV_INSTALLED = "uv_installed"
PD_CURRENT_PRESET = "current_preset"
PD_COOLDOWN = "cooldown"
PD_DAMPER = "damper"
PD_DISPLAY_HALF_POWER = "display_half_power"
PD_ECO_DELTA = "eco_delta"
PD_ENERGY_SAVING = "energy_saving"
PD_EXPENDABLES_ANODE = "expendables_anode"
PD_FIREPLACE = "fireplace"
PD_FREEZE_PROTECTION = "freeze_protection"
PD_FUNGUS_PROOF = "fungus_proof"
PD_HEATER_INSTALLED = "heater_installed"
PD_LAST_PROGRAM = "last_program"
PD_MIN_VOLTAGE = "min_voltage"
PD_NIGHT_SPEED = "night_speed"
PD_NOISELESS = "noiseless"
PD_POWER = "power"
PD_SELFCLEAN = "selfclean"
PD_SILENCE_MODE = "silence_mode"
PD_SWING_HORIZONTAL = "swing_horizontal"
PD_SWING_VERTICAL = "swing_vertical"
PD_TIME_START = "time_start"
PD_TIME_END = "time_end"
PD_TURN_ON = "turn_on"
PD_VACATION_TEMPERATURE = "vacation_temperature"

# Custom device specific values
PD_AURUS_A_AIR_CLEAN = "aurus_a_air_clean"
PD_AURUS_SCREENSAVER_MODE = "aurus_screensaver_mode"
PD_BREEZER_AUTO_INTENSITY = "breezer_auto_intensity"
PD_BREEZER_DAMPER = "breezer_damper"

PRESET_ANTI_FROST = "anti_frost"
PRESET_AUTO = "auto"
PRESET_NIGHT = "night"
PRESET_MANUAL = "manual"
PRESET_TURBO = "turbo"
PRESET_VACATION = "vacation"
PRESET_VENTILATION = "ventilation"

# Custom device specific values
PRESET_AURUS_SCREENSAVER_MODE_OFF = "screensaver_off"
PRESET_AURUS_SCREENSAVER_MODE_1 = "screensaver_1"
PRESET_AURUS_SCREENSAVER_MODE_3 = "screensaver_3"
PRESET_AURUS_SCREENSAVER_MODE_5 = "screensaver_5"

PRESET_MELODY_BIRDS_SINGING = "melody_birds_singing"
PRESET_MELODY_FIREPLACE_SOUND = "melody_fireplace_sound"
PRESET_MELODY_FOREST_SOUND = "melody_forest_sound"
PRESET_MELODY_RAIN_SOUND = "melody_rain_sound"
PRESET_MELODY_SEA_SOUND = "melody_sea_sound"

PRESET_NIGHT_MODE_OFF = "night_mode_off"
PRESET_NIGHT_MODE_AGED = "night_mode_aged"
PRESET_NIGHT_MODE_CHILD = "night_mode_child"
PRESET_NIGHT_MODE_STANDARD = "night_mode_standard"
PRESET_NIGHT_MODE_TEEN = "night_mode_teen"

PRESET_TOSHIBA_POWER_50 = "power_50"
PRESET_TOSHIBA_POWER_75 = "power_75"
PRESET_TOSHIBA_POWER_100 = "power_100"

PRESET_TOSHIBA_NOISELESS_OFF = "noiseless_off"
PRESET_TOSHIBA_NOISELESS_1 = "noiseless_1"
PRESET_TOSHIBA_NOISELESS_2 = "noiseless_2"

FEATURE_ACCESS_CONTROL = "access_control"
FEATURE_ANTI_MELDEW = "anti_meldew"
FEATURE_BACKLIGHT = "backlight"
FEATURE_BSS = "bss"
FEATURE_CHILD_LOCK = "child_lock"
FEATURE_CURRENT_CO2 = "current_co2"
FEATURE_CURRENT_TEMPERATURE = "current_temperature"
FEATURE_DAMPER = "damper"
FEATURE_ECO_AS_SMART_MODE = "energy_saving"
FEATURE_ERROR = "error"
FEATURE_EXPENDABLES_ANODE = "expendables_anode"
FEATURE_EXPENDABLES_FILTER = "expendables_filter"
FEATURE_EXPENDABLES_PREFILTER = "expendables_prefilter"
FEATURE_IONIZATION = "ionization"
FEATURE_KEEP_WARM = "keep_warm"
FEATURE_NIGHT = "night"
FEATURE_POWER_LEVEL = "power_level"
FEATURE_SMART_MODE = "smart_mode"
FEATURE_TANK = "tank"
FEATURE_TIMER = "timer"
FEATURE_TURBO = "turbo"
FEATURE_ULTRAVIOLET = "ultraviolet"
FEATURE_VOLUME = "volume"
FEATURE_WARM_STREAM = "warm_stream"

# Custom device specific features
FEATURE_AURUS_PF_AUTO_OFF_DISPLAY = "aurus_pf_auto_off_display"
FEATURE_AURUS_PF_HALF_POWER = "aurus_pf_half_power"
FEATURE_AURUS_SCREENSAVER_MODE = "aurus_screensaver_mode"
FEATURE_AURUS_VRF_CHILD_LOCK = "aurus_vrf_child_lock"
FEATURE_AURUS_VRF_ECO_MODE = "aurus_vrf_eco_mode"
FEATURE_AURUS_VRF_NOISELESS_MODE = "aurus_vrf_noiseless_mode"
FEATURE_BREEZER_DAMPER = "breezer_damper"
FEATURE_BREEZER_MELODY = "breezer_melody"
FEATURE_BREEZER_TEMPERATURE = "breezer_temperature"
FEATURE_KETTLE_TEMPERATURE_PRESET = "kettle_temperature_preset"
FEATURE_GOLDSTAR_GSTI_BREEZE_AWAY = "breeze_away"
FEATURE_GOLDSTAR_GSTI_CLEAN = "selfclean"
FEATURE_GOLDSTAR_GSTI_DAMPER = "goldstar_gsti_damper"
FEATURE_GOLDSTAR_GSTI_FREEZE_PROTECTION = "freeze_protection"
FEATURE_SHUFT_SFMS_07_09_FREEZE_PROTECTION = "freeze_protection"
FEATURE_SHUFT_SFMS_09_ANTI_MELDEW = "shuft_sfms_09_anti_meldew"

PROFILE_TYPE_AC = "ac"
PROFILE_TYPE_BOILER = "boiler"
PROFILE_TYPE_BREEZER = "breezer"
PROFILE_TYPE_HEATER = "heater"
PROFILE_TYPE_KETTLE = "kettle"

TRANLATION_KEY_CLIMATE = DOMAIN + "_climate"
TRANLATION_KEY_FAN = DOMAIN + "_fan"

ZEROCONF_CURVE = "curve"
ZEROCONF_DEVICE_TYPE = "devtype"
ZEROCONF_MAC_ADDRESS = "macaddr"
