DOMAIN = "syncleo"

VENDOR_RUSCLIMATE = "rusclimate"
VENDOR_POLARIS = "polaris"

CONF_ATTRIBUTES = "attributes"
CONF_FIRMWARE = "firmware"
CONF_MANUFACTURER = "manufacturer"
CONF_PROTOCOL = "protocol"
CONF_PUBLIC_KEY = "public"
CONF_VENDOR = "vendor"

PD_ANTI_FROST_TEMP = "anti_frost_temp"
PD_AUTO_OFF_DISPLAY = "auto_off_display"
PD_ECO_DELTA = "eco_delta"
PD_HALF_POWER = "half_power"
PD_POWER = "power"
PD_SWING_MODE = "swing_mode"
PD_TURN_ON = "turn_on"

PRESET_ANTI_FROST = "anti_frost"

FEATURE_ACCESS_CONTROL = "access_control"
FEATURE_BACKLIGHT = "backlight"
FEATURE_CHILD_LOCK = "child_lock"
FEATURE_DAMPER = "damper"
FEATURE_ERROR = "error"
FEATURE_IONIZATION = "ionization"
FEATURE_KEEP_WARM = "keep_warm"
FEATURE_NIGHT = "night"
FEATURE_POWER_LEVEL = "power_level"
FEATURE_SMART_MODE = "smart_mode"
FEATURE_TIMER = "timer"
FEATURE_TURBO = "turbo"
FEATURE_ULTRAVIOLET = "ultraviolet"
FEATURE_VOLUME = "volume"
FEATURE_WARM_STREAM = "warm_stream"

ZEROCONF_CURVE = "curve"
ZEROCONF_DEVICE_TYPE = "devtype"
ZEROCONF_MAC_ADDRESS = "macaddr"
