name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v7"

        - name: Ruff Check
          uses: astral-sh/ruff-action@v4.1.0
          with:
            args: check --output-format=github

        - name: Ruff Format
          uses: astral-sh/ruff-action@v4.1.0
          with:
            args: format --check --diff
